name: jiwa_apps
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dotted_line: ^3.2.3
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  google_maps_flutter: ^2.12.2
  geocoding: ^3.0.0
  pretty_dio_logger: ^1.4.0
  dio: ^5.8.0+1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
